# Generated by Django 6.0.6 on 2026-06-26 00:29

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.MediaPath('avatars'), verbose_name='Avatar'),
        ),
    ]
