# Generated by Django 6.0.6 on 2026-07-18 02:20

from django.db import migrations


def set_existing_verified(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.all().update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_email_verified'),
    ]

    operations = [
        migrations.RunPython(set_existing_verified),
    ]
