# Generated by Django 6.0.6 on 2026-08-05 00:15

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_options_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.MediaPath('avatars'), validators=[core.utils.validate_file_size], verbose_name='Avatar'),
        ),
    ]
