# Generated by Django 6.0.6 on 2026-06-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(help_text='Category Name', max_length=255, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(help_text='Category Name', max_length=255, null=True, unique=True, verbose_name='Category Name'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_pt_br',
            field=models.CharField(help_text='Category Name', max_length=255, null=True, unique=True, verbose_name='Category Name'),
        ),
    ]
