# Generated by Django 6.0.6 on 2026-08-04 23:56

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_name_en_category_name_es_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Nome da categoria', max_length=255, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(help_text='Nome da categoria', max_length=255, null=True, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_es',
            field=models.CharField(help_text='Nome da categoria', max_length=255, null=True, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_pt_br',
            field=models.CharField(help_text='Nome da categoria', max_length=255, null=True, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='categories.category', verbose_name='Categoria pai'),
        ),
    ]
