# Generated by Django 6.0.6 on 2026-08-16 00:44

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Popula o slug das categorias existentes."""
    Category = apps.get_model('categories', 'Category')
    for category in Category.objects.all():
        if not category.slug:
            temp_slug = slugify(category.name)
            slug = temp_slug
            counter = 1
            while Category.objects.filter(slug=slug).exclude(pk=category.pk).exists():
                slug = f"{temp_slug}-{counter}"
                counter += 1
            category.slug = slug
            category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        # Passo 1: Adicionar campo sem unique
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL gerada automaticamente a partir do nome', max_length=255, verbose_name='URL'),
        ),
        # Passo 2: Popular slugs
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        # Passo 3: Alterar para unique
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL gerada automaticamente a partir do nome', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
