# Generated by Django 6.0.6 on 2026-06-20 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the magazine, comic book...', max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, help_text='Automatically generated url', max_length=255, unique=True, verbose_name='url')),
                ('description', models.TextField(blank=True, help_text='Optional field', null=True, verbose_name='Description')),
                ('cover', models.ImageField(upload_to='covers/', verbose_name='Cover')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('is_members_only', models.BooleanField(default=False, help_text='Exclusive content for subscribers', verbose_name='Exclusive content?')),
                ('free_pages_count', models.PositiveIntegerField(default=1, help_text='How many pages can a non-paying user read before being blocked? Default: 1.', verbose_name='Free pages')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Published in')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Edited in')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='categories.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-views_count', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pages/', verbose_name='Page Content')),
                ('page_order', models.PositiveIntegerField(verbose_name='Page Order')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='publications.publication', verbose_name='Publication')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['page_order'],
            },
        ),
    ]
