# Generated by Django 6.0.6 on 2026-06-18 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nome da revista, HQ, etc...', max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, help_text='Url gerada automaticamente', max_length=255, unique=True, verbose_name='url')),
                ('description', models.TextField(blank=True, help_text='Campo opcional', null=True, verbose_name='Descrição')),
                ('cover', models.ImageField(upload_to='covers/', verbose_name='Capa')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('is_members_only', models.BooleanField(default=False, help_text='Conteúdo exclusivo para assinantes', verbose_name='Conteúdo exclusivo?')),
                ('free_pages_count', models.PositiveIntegerField(default=1, help_text='Quantas páginas um usuário não pagante pode ler antes de ser bloqueado. Padrão: 1.', verbose_name='Páginas gratuitas')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Publicado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='categories.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
                'ordering': ['-views_count', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pages/', verbose_name='Conteúdo das Páginas')),
                ('page_order', models.PositiveIntegerField(verbose_name='Ordem da Página')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='publications.publication', verbose_name='Publicação')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['page_order'],
            },
        ),
    ]
