# Generated by Django 6.0.6 on 2026-06-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='description_en',
            field=models.TextField(blank=True, help_text='Optional field', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_es',
            field=models.TextField(blank=True, help_text='Optional field', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='publication',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='Optional field', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_en',
            field=models.CharField(help_text='Name of the magazine, comic book...', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_es',
            field=models.CharField(help_text='Name of the magazine, comic book...', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='publication',
            name='title_pt_br',
            field=models.CharField(help_text='Name of the magazine, comic book...', max_length=255, null=True, verbose_name='Title'),
        ),
    ]
