# Generated by Django 6.0.6 on 2026-06-26 00:29

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publication_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(upload_to=core.utils.MediaPath('pages'), verbose_name='Page Content'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cover',
            field=models.ImageField(upload_to=core.utils.MediaPath('covers'), verbose_name='Cover'),
        ),
    ]
