# Generated by Django 6.0.6 on 2026-08-04 23:56

import core.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_options_alter_category_name_and_more'),
        ('publications', '0004_alter_page_image_alter_publication_cover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['page_order'], 'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-views_count', '-published_at'], 'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='publications.publication', verbose_name='Publicação'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(upload_to=core.utils.MediaPath('pages'), verbose_name='Conteúdo da página'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_order',
            field=models.PositiveIntegerField(verbose_name='Ordem da página'),
        ),
        migrations.AlterField(
            model_name='page',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='publications.publication', verbose_name='Publicação'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='categories.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cover',
            field=models.ImageField(upload_to=core.utils.MediaPath('covers'), verbose_name='Capa'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description',
            field=models.TextField(blank=True, help_text='Campo opcional', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description_en',
            field=models.TextField(blank=True, help_text='Campo opcional', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description_es',
            field=models.TextField(blank=True, help_text='Campo opcional', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='Campo opcional', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='free_pages_count',
            field=models.PositiveIntegerField(default=1, help_text='Quantas páginas um usuário não pagante pode ler antes de ser bloqueado? Padrão: 1.', verbose_name='Páginas gratuitas'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='is_members_only',
            field=models.BooleanField(default=False, help_text='Conteúdo exclusivo para assinantes', verbose_name='Conteúdo exclusivo?'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publicado em'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL gerada automaticamente', max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(help_text='Nome da revista, quadrinho...', max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title_en',
            field=models.CharField(help_text='Nome da revista, quadrinho...', max_length=255, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title_es',
            field=models.CharField(help_text='Nome da revista, quadrinho...', max_length=255, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title_pt_br',
            field=models.CharField(help_text='Nome da revista, quadrinho...', max_length=255, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Visualizações'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='publications.publication', verbose_name='Publicação'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
