# Generated by Django 6.0.6 on 2026-08-05 00:15

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_alter_comment_options_alter_page_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(upload_to=core.utils.MediaPath('pages'), validators=[core.utils.validate_file_size], verbose_name='Conteúdo da página'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cover',
            field=models.ImageField(upload_to=core.utils.MediaPath('covers'), validators=[core.utils.validate_file_size], verbose_name='Capa'),
        ),
    ]
