# Generated by Django 6.0.6 on 2026-08-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_options_alter_category_name_and_more'),
        ('publications', '0006_alter_page_image_alter_publication_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='category',
        ),
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='publications', to='categories.category', verbose_name='Categorias'),
        ),
    ]
