# Generated by Django 6.0.6 on 2026-08-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_remove_publication_category_publication_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desative para ocultar do site (permanece no admin)', verbose_name='Ativo'),
        ),
    ]
