# Generated by Django 6.0.6 on 2026-06-22 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, help_text='Value charged monthly for the premium subscription.', max_digits=10, verbose_name='Monthly price')),
                ('currency', models.CharField(default='usd', help_text='ISO 4217 code. Example: usd, brl, eur.', max_length=3, verbose_name='Currency')),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable the subscription checkout for users.', verbose_name='Enabled')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Subscription Settings',
                'verbose_name_plural': 'Subscription Settings',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('incomplete', 'Incomplete')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe Customer ID'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Stripe Subscription ID'),
        ),
    ]
