# Generated by Django 6.0.6 on 2026-08-04 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_subscriptionsettings_subscription_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-started_at'], 'verbose_name': 'Assinatura', 'verbose_name_plural': 'Assinaturas'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionsettings',
            options={'verbose_name': 'Configuração de assinatura', 'verbose_name_plural': 'Configurações de assinatura'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelada em'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Deixe em branco para uma assinatura que não expira.', null=True, verbose_name='Expira em'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Iniciada em'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('active', 'Ativa'), ('trialing', 'Em teste'), ('past_due', 'Atrasada'), ('canceled', 'Cancelada'), ('unpaid', 'Não paga'), ('incomplete', 'Incompleta')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ID do cliente Stripe'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ID da assinatura Stripe'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizada em'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='subscriptionsettings',
            name='currency',
            field=models.CharField(default='usd', help_text='Código ISO 4217. Exemplo: usd, brl, eur.', max_length=3, verbose_name='Moeda'),
        ),
        migrations.AlterField(
            model_name='subscriptionsettings',
            name='is_enabled',
            field=models.BooleanField(default=False, help_text='Habilita o checkout de assinatura para os usuários.', verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='subscriptionsettings',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor cobrado mensalmente pela assinatura premium.', max_digits=10, verbose_name='Preço mensal'),
        ),
        migrations.AlterField(
            model_name='subscriptionsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
