# Generated by Django 6.0.6 on 2026-08-17 16:18

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_event_id',
            field=models.CharField(blank=True, default='', help_text='ID do último evento Stripe processado (idempotência).', max_length=255, verbose_name='Último evento Stripe'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_session_id',
            field=models.CharField(blank=True, default='', help_text='Sessão de checkout em andamento (usada para evitar duplicidade).', max_length=255, verbose_name='ID da sessão de checkout Stripe'),
        ),
        migrations.AddField(
            model_name='subscriptionsettings',
            name='product_description',
            field=models.TextField(blank=True, help_text='Descrição exibida no Stripe durante o checkout (opcional).', verbose_name='Descrição do produto'),
        ),
        migrations.AddField(
            model_name='subscriptionsettings',
            name='product_image',
            field=models.ImageField(blank=True, help_text='Imagem exibida no Stripe durante o checkout (opcional).', null=True, upload_to='subscriptions', validators=[core.utils.validate_file_size], verbose_name='Imagem do produto'),
        ),
        migrations.AddField(
            model_name='subscriptionsettings',
            name='product_name',
            field=models.CharField(default='Premium Subscription', help_text='Nome exibido no Stripe durante o checkout.', max_length=255, verbose_name='Nome do produto'),
        ),
        migrations.AddField(
            model_name='subscriptionsettings',
            name='stripe_price_id',
            field=models.CharField(blank=True, default='', help_text='Preenchido automaticamente após a criação no Stripe.', max_length=255, verbose_name='ID do preço Stripe'),
        ),
        migrations.AddField(
            model_name='subscriptionsettings',
            name='stripe_product_id',
            field=models.CharField(blank=True, default='', help_text='Preenchido automaticamente após a criação no Stripe.', max_length=255, verbose_name='ID do produto Stripe'),
        ),
    ]
