# Generated by Django 6.0.6 on 2026-06-18 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Site', max_length=100, verbose_name='Título do site')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='website/logo', verbose_name='Logo do site')),
                ('background', models.ImageField(blank=True, null=True, upload_to='website/background', verbose_name='Background do site')),
                ('light_theme_primary', models.CharField(default='#FFFFFF', help_text='Exemplo: #FFFFFF', max_length=7, verbose_name='Cor Principal (Tema Claro)')),
                ('light_theme_secondary', models.CharField(default='#F8F9FA', max_length=7, verbose_name='Cor de Fundo (Tema Claro)')),
                ('dark_theme_primary', models.CharField(default='#121212', help_text='Exemplo: #121212', max_length=7, verbose_name='Cor Principal (Tema Escuro)')),
                ('dark_theme_secondary', models.CharField(default='#1A1A1A', max_length=7, verbose_name='Cor de Fundo (Tema Escuro)')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configuraçoes do Site',
            },
        ),
        migrations.CreateModel(
            name='CarouselBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='website/carousel/', verbose_name='Imagem do Banner')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('web_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='website.websettings', verbose_name='Configuração do Site')),
            ],
            options={
                'verbose_name': 'Banner Carrossel do Site',
                'verbose_name_plural': 'Banners Carrossel do Site',
                'ordering': ['order'],
            },
        ),
    ]
