# Generated by Django 6.0.6 on 2026-06-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Site', max_length=100, verbose_name='Website title')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='website/logo', verbose_name='Website logo')),
                ('background', models.ImageField(blank=True, null=True, upload_to='website/background', verbose_name='Website background')),
                ('light_theme_primary', models.CharField(default='#FFFFFF', help_text='Example: #FFFFFF', max_length=7, verbose_name='Primary Background Color (Light Theme)')),
                ('light_theme_secondary', models.CharField(default='#F8F9FA', help_text='Example: #F8F9FA', max_length=7, verbose_name='Secondary Background Color (Light Theme)')),
                ('dark_theme_primary', models.CharField(default='#121212', help_text='Example: #121212', max_length=7, verbose_name='Primary Background Color (Dark Theme)')),
                ('dark_theme_secondary', models.CharField(default='#1A1A1A', help_text='Example: #1A1A1A', max_length=7, verbose_name='Secondary Background Color (Dark Theme)')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
