# Generated by Django 6.0.6 on 2026-06-24 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websettings',
            name='background_mobile',
            field=models.ImageField(blank=True, help_text='Background used only on mobile devices. Falls back to the main background if empty.', null=True, upload_to='website/background', verbose_name='Website background (mobile)'),
        ),
    ]
