# Generated by Django 6.0.6 on 2026-06-26 00:29

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_websettings_background_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websettings',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.MediaPath('website/background'), verbose_name='Website background'),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='background_mobile',
            field=models.ImageField(blank=True, help_text='Background used only on mobile devices. Falls back to the main background if empty.', null=True, upload_to=core.utils.MediaPath('website/background'), verbose_name='Website background (mobile)'),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.MediaPath('website/logo'), verbose_name='Website logo'),
        ),
    ]
