# Generated by Django 6.0.6 on 2026-08-04 23:56

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_websettings_background_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websettings',
            options={'verbose_name': 'Configuração do site', 'verbose_name_plural': 'Configurações do site'},
        ),
        migrations.AlterField(
            model_name='websettings',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.MediaPath('website/background'), verbose_name='Fundo do site'),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='background_mobile',
            field=models.ImageField(blank=True, help_text='Fundo usado apenas em dispositivos móveis. Usa o fundo principal se vazio.', null=True, upload_to=core.utils.MediaPath('website/background'), verbose_name='Fundo do site (mobile)'),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='dark_theme_primary',
            field=models.CharField(default='#121212', help_text='Exemplo: #121212', max_length=7, verbose_name='Cor primária (tema escuro)'),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='dark_theme_secondary',
            field=models.CharField(default='#1A1A1A', help_text='Exemplo: #1A1A1A', max_length=7, verbose_name='Cor secundária (tema escuro)'),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='light_theme_primary',
            field=models.CharField(default='#FFFFFF', help_text='Exemplo: #FFFFFF', max_length=7, verbose_name='Cor primária (tema claro)'),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='light_theme_secondary',
            field=models.CharField(default='#F8F9FA', help_text='Exemplo: #F8F9FA', max_length=7, verbose_name='Cor secundária (tema claro)'),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.MediaPath('website/logo'), verbose_name='Logo do site'),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='title',
            field=models.CharField(default='Site', max_length=100, verbose_name='Título do site'),
        ),
    ]
