# Generated by Django 6.0.6 on 2026-08-05 00:15

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_websettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websettings',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.MediaPath('website/background'), validators=[core.utils.validate_file_size], verbose_name='Fundo do site'),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='background_mobile',
            field=models.ImageField(blank=True, help_text='Fundo usado apenas em dispositivos móveis. Usa o fundo principal se vazio.', null=True, upload_to=core.utils.MediaPath('website/background'), validators=[core.utils.validate_file_size], verbose_name='Fundo do site (mobile)'),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.MediaPath('website/logo'), validators=[core.utils.validate_file_size], verbose_name='Logo do site'),
        ),
    ]
