# Generated by Django 6.0.6 on 2026-08-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_websettings_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websettings',
            name='privacy_policy',
            field=models.TextField(blank=True, verbose_name='Política de Privacidade'),
        ),
        migrations.AddField(
            model_name='websettings',
            name='terms',
            field=models.TextField(blank=True, verbose_name='Termos de Uso'),
        ),
    ]
