# Generated by Django 6.0.6 on 2026-08-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_websettings_privacy_policy_websettings_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='websettings',
            name='privacy_policy_en',
            field=models.TextField(blank=True, null=True, verbose_name='Política de Privacidade'),
        ),
        migrations.AddField(
            model_name='websettings',
            name='privacy_policy_es',
            field=models.TextField(blank=True, null=True, verbose_name='Política de Privacidade'),
        ),
        migrations.AddField(
            model_name='websettings',
            name='privacy_policy_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='Política de Privacidade'),
        ),
        migrations.AddField(
            model_name='websettings',
            name='terms_en',
            field=models.TextField(blank=True, null=True, verbose_name='Termos de Uso'),
        ),
        migrations.AddField(
            model_name='websettings',
            name='terms_es',
            field=models.TextField(blank=True, null=True, verbose_name='Termos de Uso'),
        ),
        migrations.AddField(
            model_name='websettings',
            name='terms_pt_br',
            field=models.TextField(blank=True, null=True, verbose_name='Termos de Uso'),
        ),
    ]
