# Generated by Django 6.0.6 on 2026-08-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_websettings_privacy_policy_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websettings',
            name='start_message',
            field=models.TextField(blank=True, help_text='Exibida em um modal na página inicial. Deixe vazio para desativar.', verbose_name='Mensagem de aviso'),
        ),
        migrations.AddField(
            model_name='websettings',
            name='start_message_en',
            field=models.TextField(blank=True, help_text='Exibida em um modal na página inicial. Deixe vazio para desativar.', null=True, verbose_name='Mensagem de aviso'),
        ),
        migrations.AddField(
            model_name='websettings',
            name='start_message_es',
            field=models.TextField(blank=True, help_text='Exibida em um modal na página inicial. Deixe vazio para desativar.', null=True, verbose_name='Mensagem de aviso'),
        ),
        migrations.AddField(
            model_name='websettings',
            name='start_message_pt_br',
            field=models.TextField(blank=True, help_text='Exibida em um modal na página inicial. Deixe vazio para desativar.', null=True, verbose_name='Mensagem de aviso'),
        ),
    ]
