# Generated by Django 6.0.6 on 2026-08-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_websettings_start_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websettings',
            name='description',
            field=models.TextField(blank=True, help_text='Usada como meta description de SEO', verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='websettings',
            name='description_en',
            field=models.TextField(blank=True, help_text='Usada como meta description de SEO', null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='websettings',
            name='description_es',
            field=models.TextField(blank=True, help_text='Usada como meta description de SEO', null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='websettings',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='Usada como meta description de SEO', null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='websettings',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Exibido após o título nas meta tags de SEO', max_length=200, verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='websettings',
            name='subtitle_en',
            field=models.CharField(blank=True, help_text='Exibido após o título nas meta tags de SEO', max_length=200, null=True, verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='websettings',
            name='subtitle_es',
            field=models.CharField(blank=True, help_text='Exibido após o título nas meta tags de SEO', max_length=200, null=True, verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='websettings',
            name='subtitle_pt_br',
            field=models.CharField(blank=True, help_text='Exibido após o título nas meta tags de SEO', max_length=200, null=True, verbose_name='Subtítulo'),
        ),
    ]
