# Generated by Django 6.0.6 on 2026-08-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_websettings_description_websettings_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websettings',
            name='description',
            field=models.TextField(blank=True, help_text='Usada como meta description de SEO (Limite de 200 caracteres)', max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='description_en',
            field=models.TextField(blank=True, help_text='Usada como meta description de SEO (Limite de 200 caracteres)', max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='description_es',
            field=models.TextField(blank=True, help_text='Usada como meta description de SEO (Limite de 200 caracteres)', max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='Usada como meta description de SEO (Limite de 200 caracteres)', max_length=200, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Exibido após o título nas meta tags de SEO (Limite de 100 caracteres)', max_length=100, null=True, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='subtitle_en',
            field=models.CharField(blank=True, help_text='Exibido após o título nas meta tags de SEO (Limite de 100 caracteres)', max_length=100, null=True, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='subtitle_es',
            field=models.CharField(blank=True, help_text='Exibido após o título nas meta tags de SEO (Limite de 100 caracteres)', max_length=100, null=True, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='websettings',
            name='subtitle_pt_br',
            field=models.CharField(blank=True, help_text='Exibido após o título nas meta tags de SEO (Limite de 100 caracteres)', max_length=100, null=True, verbose_name='Subtítulo'),
        ),
    ]
