# Generated by Django 6.0.6 on 2026-08-22 20:48

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_alter_websettings_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo')),
                ('image', models.ImageField(blank=True, help_text='Obrigatório se não for script.', null=True, upload_to=core.utils.MediaPath('website/banners'), validators=[core.utils.validate_file_size], verbose_name='Imagem')),
                ('link', models.URLField(blank=True, verbose_name='Link')),
                ('script', models.TextField(blank=True, help_text='Cole o script HTML. Se preenchido, ignora imagem/link.', verbose_name='Script')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='website.websettings', verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order'],
            },
        ),
    ]
