# Generated by Django 6.0.6 on 2026-08-22 21:03

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_alter_advertisements_type'),
        ('website', '0012_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='link',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='script',
        ),
        migrations.AddField(
            model_name='banner',
            name='advertisement',
            field=models.ForeignKey(blank=True, help_text='Se preenchido, ignora a imagem.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='advertisements.advertisements', verbose_name='Anúncio'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Obrigatório se não houver anúncio vinculado.', null=True, upload_to=core.utils.MediaPath('website/banners'), validators=[core.utils.validate_file_size], verbose_name='Imagem'),
        ),
    ]
