# Generated by Django 6.0.6 on 2026-08-26 16:12

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0007_alter_advertisements_position'),
        ('website', '0013_remove_banner_link_remove_banner_script_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_mobile',
            field=models.ImageField(blank=True, help_text='Opcional — 640×360 recomendado, usado em ≤768px. Se vazio, usa a imagem desktop.', null=True, upload_to=core.utils.MediaPath('website/banners/mobile'), validators=[core.utils.validate_file_size], verbose_name='Imagem (Mobile)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='advertisement',
            field=models.ForeignKey(blank=True, help_text='Se preenchido, ignora a imagem. Somente SmartLink.', limit_choices_to={'is_active': True, 'type': 'smart_link'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='advertisements.advertisements', verbose_name='Anúncio'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='Obrigatório se não houver anúncio vinculado. Recomendado 1248×250 (5:1).', null=True, upload_to=core.utils.MediaPath('website/banners'), validators=[core.utils.validate_file_size], verbose_name='Imagem (Desktop)'),
        ),
    ]
