# Generated by Django 6.0.6 on 2026-08-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_banner_image_mobile_alter_banner_advertisement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websettings',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='Separadas por vírgula. Ex: revista, ebook, quadrinhos', max_length=500, verbose_name='Palavras-chave SEO'),
        ),
    ]
