# Generated by Django 6.0.6 on 2026-08-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(help_text='Cole o script HTML completo ou uma URL. Se começar com "<script", será renderizado como script; caso contrário, será tratado como link.', verbose_name='Link/Script')),
                ('type', models.CharField(choices=[('pop_under', 'Pop-under'), ('social_bar', 'Social Bar'), ('smart_link', 'Smart Link'), ('native_banner', 'Native Banner')], max_length=20, verbose_name='Tipo de anúncio')),
                ('position', models.CharField(choices=[('banner', 'Carrossel de banners'), ('card', 'Card de publicações'), ('left', 'Lateral esquerda'), ('right', 'Lateral direita'), ('preview', 'Reader preview')], max_length=20, verbose_name='Posição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Anúncio',
                'verbose_name_plural': 'Anúncios',
                'ordering': ['id'],
            },
        ),
    ]
