# Generated by Django 6.0.6 on 2026-08-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='type',
            field=models.CharField(choices=[('pop_under', 'Popunder é um anúncio em tela cheia que abre em uma aba separada, com cobrança por CPM/CPA e frequência/cliques ajustáveis.'), ('social_bar', 'Social Bar é um anúncio interativo e personalizável, ideal para sites com boa UX, usuários iOS e contorno de bloqueadores de anúncios.   '), ('smart_link', 'Smartlink direciona cada usuário para a melhor oferta automaticamente, com base em seus dados, sendo ideal para redes sociais e sites com pouco espaço para anúncios.'), ('native_banner', 'Banner nativo é um anúncio que se integra ao conteúdo do site, sendo responsivo e ideal para sites e blogs com conteúdo destacado.')], max_length=20, verbose_name='Tipo de anúncio'),
        ),
    ]
