# Generated by Django 6.0.6 on 2026-08-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_alter_advertisements_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisements',
            name='ratings_count',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de cliques no anúncio', verbose_name='Cliques'),
        ),
        migrations.AddField(
            model_name='advertisements',
            name='title',
            field=models.CharField(blank=True, help_text='Título exibido no card de anúncio', max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='advertisements',
            name='type',
            field=models.CharField(choices=[('pop_under', 'Popunder: Anúncio em tela cheia aberto em outra aba'), ('social_bar', 'SocialBar: Anúncio interativo e personalizável'), ('smart_link', 'Smartlink: Direciona o usuário à melhor oferta'), ('native_banner', 'Nativo: Anúncio integrado ao conteúdo do site')], max_length=20, verbose_name='Tipo de anúncio'),
        ),
    ]
