# Generated by Django 6.0.6 on 2026-08-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_advertisements_ratings_count_advertisements_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='position',
            field=models.CharField(choices=[('banner', 'Carrossel de banners'), ('card', 'Card de publicações'), ('left', 'Lateral esquerda'), ('right', 'Lateral direita'), ('preview', 'Reader preview'), ('footer', 'Acima do footer')], max_length=20, verbose_name='Posição'),
        ),
    ]
