# Generated by Django 6.0.6 on 2026-08-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0005_alter_advertisements_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='position',
            field=models.CharField(choices=[('banner', 'Carrossel de banners'), ('card', 'Card de publicações'), ('left', 'Lateral esquerda'), ('right', 'Lateral direita'), ('preview', 'Reader preview (Desktop)'), ('mobile', 'Reader preview (Mobile)'), ('footer', 'Acima do footer (Desktop)'), ('footer_mobile', 'Acima do footer (Mobile)')], max_length=20, verbose_name='Posição'),
        ),
    ]
