# Generated by Django 6.0.6 on 2026-08-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_alter_advertisements_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='position',
            field=models.CharField(blank=True, choices=[('banner', 'Carrossel de banners'), ('card', 'Card de publicações'), ('left', 'Lateral esquerda (Desktop)'), ('right', 'Lateral direita (Desktop)'), ('preview', 'Reader preview (Desktop)'), ('mobile', 'Reader preview (Mobile)'), ('footer', 'Acima do footer (Desktop)'), ('footer_mobile', 'Acima do footer (Mobile)')], help_text='Não necessário para SocialBar', max_length=20, verbose_name='Posição'),
        ),
    ]
